[package]
name = "tuktak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssh = "0.9.9"
async-std = { version = "1", features = ["attributes", "tokio1"] }
